name: Deploy ReportFrom Develop
on:
  push:
    branches:
      - develop
    paths:
      - 'DataManager/ReportForm/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
  env:
  steps:
    - name: Setup repository
      uses: actions/checkout@v2

    - name: Steup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Clasp
      run: npm install -g @google/clasp

      # ログイン情報取得
      # 環境別定数生成

    - name: Push
      run: |
        cd DataManager/ReportForm
        clasp push --force
    - name: DEPLOY
      run: |
        cd DataManager/ReportForm
        clasp deploy