name: Update Music Table Production
on:
  workflow_dispatch:
    inputs:
jobs:
  update-music-table:
    runs-on: ubuntu-latest
    env:
      REPORTFORM_SERVER_URL: ${{ secrets.REPORTFORM_PRODUCTION_SERVER_URL }}
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: true

      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Update Music Table
        run: "dotnet run --project Core.NET/ChunithmCLI -- \
          update-music-table \
          --sega-id ${{ secrets.CLI_SEGA_ID }} \
          --password ${{ secrets.CLI_SEGA_PASSWORD }} \
          --aime-index ${{ secrets.CLI_SEGA_AIME_INDEX }} \
          --max-level 21 \
          --db-url $REPORTFORM_SERVER_URL"